// <auto-generated />
namespace Niagara_Hospice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class SubRoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SubRoles));
        
        string IMigrationMetadata.Id
        {
            get { return "201502171556323_SubRoles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
